### PR TITLE
Tweak pairing micro:bit wording and adding a step for pin

### PR DESCRIPTION
**Pull request by microbit-grace**
Task: https://microbit-global.monday.com/boards/1162890768/pulses/1459857054

- Added enter pin if needed instruction step to pairing flow
- Remove 30 sec warning text
- Tweaked searching for micro:bit text

**Preview of added step in pairing flow**
73078A95-922A-4673-B810-4A5D57638FF1

### CODE REVIEW

**Comment by microbit-grace** [comment]
Thanks @martinwork for the feedback re removing the 30 secs warning, Lucy has agreed with you and I have removed it. She also made some new comments in the [paper doc link](https://paper.dropbox.com/doc/Pairing-flow--CNAhvnzz~RwfPMeF7XzbHWEmAQ-D4REAjCL8BGPtx3PWkY0C) regarding the text while "Searching for micro:bit" part. What do you think? Please feel free to add the comments directly on the paper doc. Thank you!

**Review by microbit-matt-hillsdon — APPROVED** [review]
UI changes seem fine.
Worth confirming with Lucy we're happy with the emphasis that having the GIF before the "if you're asked" text gives to pressing button A (given few folks will encounter it).

I had a bit of a 4 dialog pairing disaster but that also happens for me on main.

**Comment by microbit-grace** [comment]
73078A95-922A-4673-B810-4A5D57638FF1

**Review by microbit-matt-hillsdon — APPROVED** [review]
LGTM

**Pull request merged**
