### PR TITLE
Relabel and arrange menu items

### PR DESCRIPTION
**Pull request by microbit-grace**
Task: https://microbit-global.monday.com/boards/1162890768/pulses/1457889927

Update menu items ordering so that it is more like the iOS app:
- Create Code
- My Programs
- Manage Connections
- Project Ideas

### CODE REVIEW

**Comment by martinwork** [comment]
@microbit-grace @jaustin 

I already did this in my branch with the new flash-pair flow
https://github.com/martinwork/microbit-android/tree/new-flash-pair-flow

I wondered if "Manage Connections" might be too long as a page tile on some phones, and if it was was unnecessarily grand for Pair. The iOS app supports more than one pairing and removing a connection.

It all looks good, so I am happy for you to merge, and I'll fix up my branch.

**Comment by microbit-grace** [comment]
Thanks @martinwork, I have reverted the change from "Manage Connections" to "Pair and copied your change from your new flash flow PR so that the header in the My Programs page is also updated to not show "Flash"

**Comment by martinwork** [comment]
Oh yes @microbit-grace, I had forgotten about needing to make that change. Beware... I seem to remember one or two of those strings were reused in not-really-related places... or maybe it was just that there were two strings for Flash.

**Comment by microbit-grace** [comment]
@martinwork Yes, I noticed that there were confusingly another "Flash" string, but I think that's for the Flash button. I haev also changed the main activity btn when they are landscape to have `textAllCaps: false`. If we want all the other buttons to not be fully capitalised, I think I might do it in a separate PR. If you are happy with changes, I shall squash and merge. Many thanks!

**Comment by microbit-matt-hillsdon** [comment]
Closing in favour of #63.

**Pull request closed without merging**
